### ISSUE TITLE
How to run using docker-compose?

### ISSUE THREAD

**Issue by vivekmiyani** [ShoshinNikita/budget-manager#162]
- I've tried the README way.
  - In which I was getting `database init error: couldn't create DB connection: database is down` error.
- Hence, I have build the project using `docker-compose up --build` and I was able to start the server.
  - But later on the browser I got 404 error.

**Comment by ShoshinNikita** [comment]
Hi. Can you share your `docker-compose` file?

**Comment by vivekmiyani** [comment]
Same as the repo's README:

```yaml
version: "2.4"

services:
  budget-manager:
    image: ghcr.io/shoshinnikita/budget-manager:latest
    container_name: budget-manager
    environment:
      STORE_BOLT_PATH: ./var/budget-manager.db
      SERVER_AUTH_BASIC_CREDS: "x:$2y$05$Gw7BNEJewa/vVGBq2ePc2ecfUCAvv7dzIngKCS8QPdpTh9oHWvA5W"
    ports:
      - "8080:8080"
    volumes:
      - ./var:/srv/var
```

Facing `database init error: couldn't create DB connection: database is down` issue.
