### ISSUE TITLE
Add search

### ISSUE THREAD

**Issue by ShoshinNikita** [ShoshinNikita/budget-manager#78]
1. Update API

    ```curl
    GET /api/search
    Content-Type: application/json
    Authorization: Basic ...
    ```

    ```yaml
    {
      "title": "foo"   # title pattern (contains)
      "notes": "sales" # notes pattern (contains)

      "after":  "2006-01-02T15:04:05Z07:00" # start date to search (`RFC3339` layout)
      "before": "2006-01-02T15:04:05Z07:00" # end date to search (`RFC3339` layout)

      "min_cost": "15.5" # minimal Spend Cost
      "max_cost": "27.3" # maximal Spend Cost

      "type_ids": "1,2,55" # list of Spend Type ids separated by comma
    }
    ```

1. Add a page with url `/search`. It supports all params from API but consumes them from query parameters

**Comment by ShoshinNikita** [comment]
Request body should also contain `title_exactly` and `notes_exactly` params. Updated body:

```yaml
{
  "title": "foo",        # title pattern (contains)
  "title_exactly": false # defines should we search exactly for the passed title

  "notes": "sales"       # notes pattern (contains)
  "notes_exactly": false # defines should we search exactly for the passed notes

  "after":  "2006-01-02T15:04:05Z07:00" # start date to search (`RFC3339` layout)
  "before": "2006-01-02T15:04:05Z07:00" # end date to search (`RFC3339` layout)

  "min_cost": "15.5" # minimal Spend Cost
  "max_cost": "27.3" # maximal Spend Cost

  "type_ids": "1,2,55" # list of Spend Type ids separated by comma
}
```
